import { useEffect, useRef } from "react";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { toast } from "sonner";
import { AuthLayout } from "@/components/site/AuthLayout";
import { OtpVerification, type VerifyResult } from "@/components/verify/OtpVerification";
import { supabase } from "@/integrations/supabase/client";

type Search = { email?: string | undefined };

export const Route = createFileRoute("/verify-email")({
  validateSearch: (search: Record<string, unknown>): Search => ({
    email: typeof search['email'] === "string" ? (search['email'] as string) : undefined,
  }),
  head: () => ({
    meta: [
      { title: "Verify your email — Gigz Exchange" },
      { name: "description", content: "Enter the verification code we emailed you to activate your Gigz Exchange account." },
      { property: "og:title", content: "Verify your email — Gigz Exchange" },
      { property: "og:description", content: "Confirm your email address and enter the Gigz Exchange dashboard." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: VerifyEmailPage,
});

function VerifyEmailPage() {
  const navigate = useNavigate();
  const { email } = Route.useSearch();
  const sentAt = useRef(Date.now());
  const CODE_TTL_MS = 10 * 60 * 1000; // matches the 10-minute expiry set in request_email_verification()
  const requestedOnce = useRef(false);

  // Send the first code automatically when this page loads (covers the
  // case where the user lands here right after signup and hasn't
  // received a code yet).
  useEffect(() => {
    if (requestedOnce.current) return;
    requestedOnce.current = true;
    supabase.rpc("request_email_verification").then(({ error }) => {
      if (error) toast.error(error.message);
    });
  }, []);

  const verify = async (code: string): Promise<VerifyResult> => {
    const { error } = await supabase.rpc("verify_email_code", { _code: code });
    if (!error) return true;
    if (Date.now() - sentAt.current > CODE_TTL_MS) {
      return { ok: false, title: "Code expired", message: "Request a new verification code to continue." };
    }
    return {
      ok: false,
      title: "Invalid verification code",
      message: error.message || "Please check your email and try again.",
    };
  };

  const resend = async () => {
    const { error } = await supabase.rpc("request_email_verification");
    if (error) toast.error(error.message);
    else {
      sentAt.current = Date.now();
      toast.success("Verification code sent", { description: email ? `We emailed a new code to ${email}.` : "Check your inbox." });
    }
  };

  return (
    <AuthLayout
      title="Verify your email"
      subtitle={
        email
          ? `We sent a verification code to ${email}. Enter it below to activate your Gigz Exchange account.`
          : "Enter the verification code Gigz Exchange emailed you."
      }
      footer={
        <>
          Wrong address?{" "}
          <Link to="/register" className="font-semibold text-foreground hover:text-accent">Start over</Link>
        </>
      }
    >
      <OtpVerification
        length={6}
        resendSeconds={60}
        phoneNumber={email ?? "your email address"}
        title="Enter verification code"
        description={
          <>
            Enter the 6-digit code sent to{" "}
            <span className="font-medium text-foreground">{email ?? "your email address"}</span>
          </>
        }
        onVerify={verify}
        onResend={resend}
        onContinue={() => void navigate({ to: "/dashboard" })}
      />
      <p className="mt-4 text-center text-xs text-muted-foreground">
        The code is generated by Gigz Exchange and sent only to your email address. It expires in 10 minutes —
        request a new one if it stops working.
      </p>
    </AuthLayout>
  );
}
