import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { toast } from "sonner";
import { AuthLayout } from "@/components/site/AuthLayout";
import { OtpVerification, type VerifyResult } from "@/components/verify/OtpVerification";
import { supabase } from "@/integrations/supabase/client";

type Search = { email?: string | undefined };

export const Route = createFileRoute("/verify-email")({
  validateSearch: (search: Record<string, unknown>): Search => ({
    email: typeof search['email'] === "string" ? (search['email'] as string) : undefined,
  }),
  head: () => ({
    meta: [
      { title: "Verify your email — Gigz Exchange" },
      { name: "description", content: "Enter the verification code we emailed you to activate your Gigz Exchange account." },
      { property: "og:title", content: "Verify your email — Gigz Exchange" },
      { property: "og:description", content: "Confirm your email address and enter the Gigz Exchange dashboard." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: VerifyEmailPage,
});

function VerifyEmailPage() {
  const navigate = useNavigate();
  const { email } = Route.useSearch();

  const verify = async (code: string): Promise<VerifyResult> => {
    if (!email) {
      return {
        ok: false,
        title: "Missing email address",
        message: "Start again from registration so we know which address to verify.",
      };
    }
    // Real verification against the authentication provider's email OTP.
    const { data, error } = await supabase.auth.verifyOtp({ email, token: code, type: "email" });
    if (!error && data.session) return true;
    const raw = (error?.message ?? "").toLowerCase();
    if (raw.includes("expired")) {
      return { ok: false, title: "Code expired", message: "Request a new verification code to continue." };
    }
    return {
      ok: false,
      title: "Invalid verification code",
      message: "Please check your email and try again.",
    };
  };

  const resend = async () => {
    if (!email) return;
    const { error } = await supabase.auth.resend({ type: "signup", email });
    if (error) toast.error(error.message);
    else toast.success("Verification code sent", { description: `We emailed a new code to ${email}.` });
  };

  return (
    <AuthLayout
      title="Verify your email"
      subtitle={
        email
          ? `We sent a verification code to ${email}. Enter it below to activate your Gigz Exchange account.`
          : "Enter the verification code Gigz Exchange emailed you."
      }
      footer={
        <>
          Wrong address?{" "}
          <Link to="/register" className="font-semibold text-foreground hover:text-accent">Start over</Link>
        </>
      }
    >
      <OtpVerification
        length={6}
        resendSeconds={60}
        phoneNumber={email ?? "your email address"}
        title="Enter verification code"
        description={
          <>
            Enter the 6-digit code sent to{" "}
            <span className="font-medium text-foreground">{email ?? "your email address"}</span>
          </>
        }
        onVerify={verify}
        onResend={resend}
        onContinue={() => void navigate({ to: "/dashboard" })}
      />
      <p className="mt-4 text-center text-xs text-muted-foreground">
        The code is generated by Gigz Exchange authentication and sent only to your email address. It expires shortly —
        request a new one if it stops working.
      </p>
    </AuthLayout>
  );
}
