import {
  Activity,
  BarChart3,
  Building2,
  CreditCard,
  Flag,
  Gauge,
  Globe2,
  HelpCircle,
  History,
  KeyRound,
  LayoutDashboard,
  LifeBuoy,
  ListChecks,
  Package,
  PhoneCall,
  Server,
  Settings,
  ShoppingCart,
  ShieldCheck,
  Tags,
  User,
  Users,
  Wallet,
} from "lucide-react";
import type { NavItem } from "./AppShell";

export const customerNav: NavItem[] = [
  { to: "/dashboard", label: "Dashboard", icon: LayoutDashboard },
  { to: "/dashboard/buy", label: "Buy Number", icon: PhoneCall },
  { to: "/dashboard/orders", label: "Active Orders", icon: ListChecks },
  { to: "/dashboard/verify", label: "SMS Verification", icon: ShieldCheck },
  { to: "/dashboard/history", label: "Order History", icon: History },
  { to: "/dashboard/transactions", label: "Transactions", icon: CreditCard },
  { to: "/dashboard/wallet", label: "Wallet", icon: Wallet },
  { to: "/dashboard/api", label: "API", icon: KeyRound },
  { to: "/dashboard/support", label: "Support", icon: LifeBuoy },
  { to: "/dashboard/profile", label: "Profile", icon: User },
  { to: "/dashboard/settings", label: "Settings", icon: Settings },
];

export const adminNav: NavItem[] = [
  { to: "/admin", label: "Overview", icon: Gauge },
  { to: "/admin/users", label: "Users", icon: Users },
  { to: "/admin/orders", label: "Orders", icon: ShoppingCart },
  { to: "/admin/numbers", label: "Numbers", icon: Package },
  { to: "/admin/countries", label: "Countries", icon: Globe2 },
  { to: "/admin/services", label: "Services", icon: Flag },
  { to: "/admin/pricing", label: "Pricing", icon: Tags },
  { to: "/admin/transactions", label: "Transactions", icon: Activity },
  { to: "/admin/payments", label: "Payments", icon: Building2 },
  { to: "/admin/providers", label: "API Providers", icon: Server },
  { to: "/admin/support", label: "Support", icon: HelpCircle },
  { to: "/admin/reports", label: "Reports", icon: BarChart3 },
  { to: "/admin/settings", label: "Settings", icon: Settings },
];
